/*
  config.h (.cmake)
  File for settings and options, generated with cmake, used during compile steps
*/
#define DIAMOND_VERSION_MAJOR @DIAMOND_VERSION_MAJOR@
#define DIAMOND_VERSION_MINOR @DIAMOND_VERSION_MINOR@
#define DIAMOND_VERSION_BUILD @DIAMOND_VERSION_BUILD@
#define DIAMOND_VERSION "@DIAMOND_VERSION_MAJOR@.@DIAMOND_VERSION_MINOR@.@DIAMOND_VERSION_BUILD@"
#define DIAMOND_NAME "@CMAKE_PROJECT_NAME@"
